import { Inter } from 'next/font/google'
import './globals.css'
import { Nav } from './_components'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className='mt-24'>
      <Nav/>
        {children}</body>
    </html>
  )
}
