import { Inter } from "next/font/google";
import "./globals.css";
import { Nav } from "./_components";
import Footer from "./_components/Footer/Footer";
import Disclaimer from "./_components/Disclaimer/Disclaimer";
import NewsLetter from "./_components/common/Modals/NewsLetter/NewsLetter";
import { ProductContextProvider } from "./contexts/ProductsContext";
import { AuthContextProvider } from "./contexts/AuthContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SwiftSail",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ProductContextProvider>
      <AuthContextProvider>
        <html lang="en">
          <body>
            <Disclaimer />
            <Nav />
            {children}

            <Footer />
          </body>
        </html>
      </AuthContextProvider>
    </ProductContextProvider>
  );
}
