import { Inter } from 'next/font/google'
import './globals.css'
import { Nav } from './_components'
import Footer from './_components/Footer/Footer'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SwiftSail',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='mt-24 bg-gray-50 mx-72 min-h-screen'>
        {children}
        {/* <Nav/> */}
      </body>
      <Footer/>
    </html>
  )
}
